# Adds ~/.local/bin and my script folder to path.
export PATH="/usr/local/bin:$HOME/.local/bin:$HOME/.local/bin/scripts:$PATH:$HOME/.local/bin/siemens-scripts:/home/knj/.gem/ruby/2.7.0/bin:$HOME/.npm-global/bin:$HOME/.cargo/bin"
export NODE_PATH=~/.npm-global/lib/node_modules

# Set config home dir.
export XDG_CONFIG_HOME="$HOME/.config"

# Default programs:
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox-developer-edition"
export READER="okular"

# Get cam to work in teams
export XLIB_SKIP_ARGB_VISUALS=1

# Cleanup ~/ 
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Program related stuff
export LANG=en_US.UTF-8
export ZSH="$ZDOTDIR/oh-my-zsh"
export ZSH_CUSTOM="$ZDOTDIR/custom"

# Fix for Alacritty on ultra wide monitors
export WINIT_X11_SCALE_FACTOR=1

export _JAVA_AWT_WM_NONREPARENTING=1
$HOME/.cache/bw_session
