ZSH_THEME="nymann"
COMPLETION_WAITING_DOTS="true"

# History
HISTSIZE=5000
SAVEHIST=$HISTSIZE
HIST_STAMPS="%Y.%m.%d %H:%M:%S"
HISTFILE="$HOME/.cache/zsh/history"

plugins=(
    git
    colored-man-pages
    sudo
)

bindkey -v
source $ZSH/oh-my-zsh.sh
