alias sus="systemctl --user status"
alias v="nvim"
alias youtube-dl="yt-dlp"
alias nymann="cd ~/code/github.com/nymann"
alias wert="cd ~/code/github.com/wert-dk/wert-api"
alias kruhlmann="cd ~/code/github.com/Kruhlmann"
alias creditoro="cd ~/code/github.com/creditoro"
alias github="cd ~/code/github.com"
alias ydl="youtube-dl -o \"%(title)s.%(ext)s\""
alias yt="ydl --add-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias todo="calcurse -Q --filter-type todo --filter-uncompleted"
alias dotfiles="cd ~/code/github.com/nymann/dotfiles/dots"
alias sv="sudo -E nvim"
alias sysu="systemctl --user"
alias ju="journalctl --user"
alias colemak="setxkbmap -variant colemak"
alias kb="setxkbmap -variant altgr-intl"
alias senv="source .venv/bin/activate"
alias cenv="python3 -m venv .venv && senv"
alias ealiases="v ~/.config/zsh/custom/aliases.zsh"
alias edwm="v ~/code/github.com/nymann/dotfiles/dots/dwm/config.h"
alias itd="python3 -c \"import configparser; c = configparser.ConfigParser(); c.read('setup.cfg'); print(c['options']['tests_require'])\" | xargs pip install"
alias gp="git push"
alias tlog_data="python3 __init__.py --database=tlog --days=18263 --per_day=150 --table=tlog_entries"
alias lint="pylint --rcfile=setup.cfg src migrations tests"
alias fix="isort --recursive src migrations tests;yapf --style google -ipr src migrations tests"
alias test="python3 setup.py test"
alias p="cat"
alias commit="emoji_commit_selector"
alias aur="pikaur"
alias wow="~/games/battlenet/drive_c/Program\ Files\ \(x86\)/World\ of\ Warcraft/_retail_/Interface/AddOns/"
alias tbc="~/games/battlenet/drive_c/Program\ Files\ \(x86\)/World\ of\ Warcraft/_classic_/Interface/AddOns/"
alias clone=". git-clone"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias pc=".git/hooks/pre-commit"
alias startx="ssh-agent startx"
alias flakesrc="ag -l | entr -c flake8 src"
alias flaketst="ag -l | entr -c flake8 tests"
alias flakeit="ag -l | entr -c flake8 tests src"
alias mypyit="ag -l | entr -c mypy src/ tests/"
alias testit="ag -l | entr -c pytest --durations=0"
alias unit="ag -l | entr -c pytest --durations=0 tests/unit_tests"
alias integration="ag -l | entr -c pytest --durations=0 tests/integration_tests"
alias legacy="gunicorn --bind 0.0.0.0:8000 run:APP"
alias muh_node="source /usr/share/nvm/init-nvm.sh && nvm use 14"
alias muh_test="yarn jest --verbose --watch --config config/jest.config.js"
alias covwatch="cd htmlcov/ && browser-sync start --server --files index.html"
alias cmute="/home/knj/code/gitlab.nymann.dev/commutee"
alias r=". repos && clear"
