#!/bin/sh
raw="$(curl -fGsk "https://lichess.org/api/user/$1")"

if [ "$raw" = "" ] 
then
    echo ""
    exit
fi

online="$(echo $raw | jq '.online?')"
if [ -z "$online" ]
then
    echo ""
    exit
fi
if [ "$online" = false ]
then
    echo "%{F#666666}%{F-}"
    exit
fi
echo "%{F#FFFFFF}%{F-}"

