#! /bin/sh
pkill -9 shxkd
sxhkd &
wmname LG3D
xsetroot -solid black
setxkbmap -option -variant altgr-intl && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
#autorandr --change &
bspc config border_width         2
bspc config window_gap		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Android* floating=on

bash ~/.config/polybar/launch.sh
