so ~/.config/nvim/includes/plugins/vim-pydocstring.vim
so ~/.config/nvim/includes/plugins/ultisnips.vim
so ~/.config/nvim/includes/plugins/airline.vim
so ~/.config/nvim/includes/plugins/nerdtree.vim
so ~/.config/nvim/includes/plugins/rainbow.vim
so ~/.config/nvim/includes/plugins/devicons.vim
so ~/.config/nvim/includes/plugins/goyo.vim
so ~/.config/nvim/includes/plugins/markdown_preview.vim
so ~/.config/nvim/includes/plugins/vista.vim
so ~/.config/nvim/includes/plugins/fzf.vim
so ~/.config/nvim/includes/plugins/vim-floaterm.vim
