"so ~/.config/nvim/includes/plugins/ale.vim
so ~/.config/nvim/includes/plugins/ultisnips.vim
so ~/.config/nvim/includes/plugins/airline.vim
so ~/.config/nvim/includes/plugins/coc.vim
so ~/.config/nvim/includes/plugins/nerdtree.vim
so ~/.config/nvim/includes/plugins/rainbow.vim
so ~/.config/nvim/includes/plugins/devicons.vim
so ~/.config/nvim/includes/plugins/goyo.vim
so ~/.config/nvim/includes/plugins/markdown_preview.vim
