#!/usr/bin/env sh

MONITORS_NAMES=$(bspc query -M --names)

FOUND_INDEX=-1
INDEX=1
for monitor in $MONITORS_NAMES; do
	if [ $monitor = "DP-3" ]; then
		FOUND_INDEX=$INDEX
		break
	fi
	INDEX=$(expr $INDEX + 1)
done

if [ FOUND_INDEX = -1 ] ; then
	echo "Monitor DP-3 not found."
	exit 1
fi

# remove MONITOR at FOUND_INDEX

MONITOR_1=$(bspc query -M |sed -e "${FOUND_INDEX}d" | sed '1q;d')
MONITOR_2=$(bspc query -M |sed -e "${FOUND_INDEX}d" | sed '2q;d')
bspc monitor "$MONITOR_2" -d 1 3 5 7 9
bspc monitor "$MONITOR_1" -d 0 2 4 6 8
