#!/usr/bin/env sh

#MONITOR_N1=$(bspc query -M --names | sed '1q;d')
#	MONITORS=$(xrandr | grep -w "connected" | awk '{ print $1, $3 }' |


MONITOR_1=$(bspc query -M | sed '1q;d')
MONITOR_2=$(bspc query -M | sed '2q;d')
if [[ $(hostname) == 'core' ]]; then
	bspc monitor "$MONITOR_2" -d 1 2 3 4 5
	bspc monitor "$MONITOR_1" -d 0 9 8 7 6
	exit 0
fi

bspc monitor "$MONITOR_1" -d 1 2 3 4 5
bspc monitor "$MONITOR_2" -d 0 9 8 7 6

