#!/usr/bin/env sh

curl -O $1 -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0' -H 'Accept: image/webp,*/*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Cookie: viewed_cookie_policy=yes; PHPSESSID=de033ecd91e4d8a7fc0eecc7a6aa76aa; cookielawinfo-checkbox-necessary=yes'
