#!/usr/bin/env sh

curl -O $1 -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36' -H 'Accept: image/webp,*/*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Cookie: viewed_cookie_policy=yes; PHPSESSID=de033ecd91e4d8a7fc0eecc7a6aa76aa; cookielawinfo-checkbox-necessary=yes'
