#!/bin/bash

PROTOCOL=https
IP_ADDRESS=192.168.5.9
PORT=4747
ENDPOINT=mjpegfeed
RESOLUTION=$@

if ! command -v adb &> /dev/null
then
    echo "adb is not installed!"
    exit
fi

if ! command -v mpv &> /dev/null
then
    echo "mpv is not installed!"
    exit
fi

echo "waiting for the device to show up via adb"
adb wait-for-usb-device

adb forward tcp:$PORT tcp:$PORT

mpv "$PROTOCOL://$IP_ADDRESS:$PORT/$ENDPOINT?$RESOLUTION" --no-cache --untimed --no-demuxer-thread --video-sync=audio --vd-lavc-threads=1
