#!/bin/sh

sudo nvidia-smi -pm 1
sudo nvidia-smi -i 0 -pl 320
sudo nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=0'
sudo nvidia-settings -a '[gpu:0]/GPUFanControlState=1'
sudo nvidia-settings -a '[fan:0]/GPUTargetFanSpeed=80'
sudo nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffset[2]=0'
sudo nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffset[3]=0'
sudo nvidia-settings -a '[gpu:0]/GPUMemoryTransferRateOffset[4]=0'
sudo nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffset[2]=100'
sudo nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffset[3]=100'
sudo nvidia-settings -a '[gpu:0]/GPUGraphicsClockOffset[4]=100'
#pkill Xorg
