#!/usr/bin/env sh

curl -O "https://d38ynedpfya4s8.cloudfront.net/hls/p/282/sp/28200/serveFlavor/entryId/0_00cqcl10/v/2/ev/6/flavorId/0_5e7g91rq/name/a.mp4/$1" -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Origin: https://kaf-blackboard-282.kaltura.nordu.net' -H 'Connection: keep-alive' -H 'Referer: https://kaf-blackboard-282.kaltura.nordu.net/media/BOOD-UP+06+Analysis+structure+-+part+1/0_00cqcl10/290067' -H 'TE: Trailers'
