#!/bin/sh

# This script functions as a browser wrapper.
# It opens work related URLs in my work browser firefox,
# and all other URLs in my private browser; qutebrowser.

# To set this browser as default, put `export BROWSER=kek_browser`
# in your profile.

is_work_url() {
    # Called like: is_work_url url
    echo "$1" | grep 'siemens.dk\|mobnet.dk\|siemens.com' 
}

if is_work_url "$1"; then
    firefox-developer-edition -new-tab "$1"
else
    firefox-developer-edition -new-tab "$1"
    #qutebrowser --target tab "$1"
fi
