#!/usr/bin/env python3
import logging
import re
import sys
from pathlib import Path


def zero_pad(filename: Path, c: str = "E") -> Path:
    # S1E6.webm -> S01E06.webm
    m = re.search(f'{c}\\d\\D', filename.name)
    if m is None:
        logging.debug("%s didn't match", filename.name)
        return filename
    index = m.start() + 1
    b = filename.name
    l = b[:index] + '0' + b[index:]
    return filename.replace(l)

    
if __name__ == "__main__":
    logging.basicConfig(stream=sys.stdout, level=logging.INFO)
    for arg in sys.argv[1:]:
        a = zero_pad(Path(arg), c="E")
        zero_pad(a, c="S")
