#!/usr/bin/env sh

rm $HOME/.cache/dwmbar/*

ps -ef | grep "dwm_clock" | awk '{print $2}' | xargs kill -9
ps -ef | grep "dwm_mail" | awk '{print $2}' | xargs kill -9
ps -ef | grep "dwm_corona" | awk '{print $2}' | xargs kill -9

ps -ef | grep "dwm_mpd" | awk '{print $2}' | xargs kill -9

$HOME/.local/bin/dwm/dwm_clock &
$HOME/.local/bin/dwm/dwm_mail &
$HOME/.local/bin/dwm/dwm_corona &

$HOME/.local/bin/dwm/dwm_mpd &
