#!/usr/bin/env sh

rm $HOME/.cache/dwmbar/*

ps -ef | grep "dwm_clock" | awk '{print $2}' | xargs kill -9
ps -ef | grep "dwm_corona" | awk '{print $2}' | xargs kill -9
ps -ef | grep "dwm_unpaid_eth" | awk '{print $2}' | xargs kill -9
ps -ef | grep "dwm_reviews" | awk '{print $2}' | xargs kill -9
ps -ef | grep "dwm_to_dos" | awk '{print $2}' | xargs kill -9

#ps -ef | grep "dwm_mpd" | awk '{print $2}' | xargs kill -9
#ps -ef | grep "dwm_calcurse" | awk '{print $2}' | xargs kill -9

$HOME/.local/bin/scripts/dwm/dwm_clock &
$HOME/.local/bin/scripts/dwm/dwm_corona &
$HOME/.local/bin/scripts/dwm/dwm_unpaid_eth &
$HOME/.local/bin/scripts/dwm/dwm_reviews &
$HOME/.local/bin/scripts/dwm/dwm_to_dos &

#$HOME/.local/bin/scripts/dwm/dwm_mpd &
#$HOME/.local/bin/scripts/dwm/dwm_calcurse &
