#!/usr/bin/env python3

from time import sleep

from pynvim import attach


def main(path: str):
    nvim = attach(session_type="socket", path=path)
    nvim.command("CoverageLoad")
    sleep(0.2)
    nvim.command("CoverageShow")


if __name__ == "__main__":
    main(path="/tmp/kek")
