#!/usr/bin/env python3

from pathlib import Path
from time import sleep

from pynvim import attach


def main(path: Path):
    nvim = attach(session_type="socket", path=path)
    nvim.command("CoverageLoad")
    sleep(0.4)
    nvim.command("CoverageShow")


if __name__ == "__main__":
    main(path=Path.cwd().joinpath(".nvim-sock"))
