#!/usr/bin/env sh

rename_to=${2:?"Specify what the project should be renamed to."}
rename_from=${1:-fastapi_template}

grep -rl "${rename_from}" | parallel sed -i "s#${rename_from}#${rename_to}#g" {}
