#!/usr/bin/env sh

[ $(id -u) -eq 0 ] || exec sudo $0
umask 0022

DNS=10.200.200.1
GW=10.200.200.1

cat > /run/dnsmasq/wg0.conf << EOF
server=/whatsmyipaddress.com/${DNS}
EOF

systemctl restart dnsmasq
add_gateway_route() {
    ip route add "$1" via ${GW}
}

add_gateway_route "35.186.238.0/24"
